### PR TITLE
devops: Update AskNicely api endpoints to new naming

### PR DESCRIPTION
**Pull request by dkgrayson**
# Background
AskNicely is updating their API to change /person to /contact, /people to /contacts and changing various url params. This PR updates the endpoints in the SDK to match the updated endpoint naming scheme.

# Steps to test
- Follow steps in README to test
- Note - I couldn't get these steps to work so I'm not sure the best way to test
**Expected Behavior:** All endpoints work.

- Please also make sure I didn't miss updating any code. I think I got it all but I would appreciate another check.

### CODE REVIEW

**Comment by dkgrayson** [comment]
[AskNicely API changes](https://trello.com/c/b3iw22MP/4049-asknicely-api-changes)

**Comment by jfelipe** [comment]
Friends, for some reason I'm still here. Anyway, I must say this is great work. 🎖️ 👏 🚢  LGTM 🤣

**Review by jonr-luma — APPROVED** [review]
Everything works as expected, great work (and great attention to detail on some of the contact vs contacts parts, you were right some of those were weird).

**Comment by jonr-luma** [comment]
Hold up, just realized I was testing on master 🤦 Now that I know how I'm actually going to check your changes.

**Comment by jonr-luma** [comment]
Okay, I found something weird with the new api using the `add_person` method. See the images below - but basically after the update, the response says that it didn't get the email. I'm going to keep testing to see what else I can find, but figured I'd bring this up sooner rather than later.

On master:
Screen Shot 2021-07-30 at 1 26 35 PM

On 4049-asknicely-api-changes:
Screen Shot 2021-07-30 at 1 27 41 PM

**Review by jonr-luma — CHANGES_REQUESTED** [review]
It looks like the `send_survey_bulk` method is also having an issue with the email address missing.

image

**Comment by dkgrayson** [comment]
@jonr-luma I believe I have this fixed. Ready for review!

**Comment by dkgrayson** [comment]
@jonr-luma Will you remove the screenshot with API keys please

**Review by jonr-luma — APPROVED** [review]
Looks good! both of those endpoints are working now. Nice work!

**Pull request merged**
